name: buildfork
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://long-hill.surge.sh
    steps:
      - name: Download the Build Artifact
        uses: actions/download-artifact@4.1.2
        with: 
          name: build
      - name:  deploy to surge
        run: npx surge --project '.' --domain long-hill.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.0.0
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage
        uses: actions/upload-artifact@v4.3.1
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build file
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build
          path : build
